# To start a cluster 

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30007
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30008
- role: worker
  extraPortMappings:
  - containerPort: 30007
    hostPort: 30009


# kind create cluster --config <config_path> --name <cluster_name>
# kind delete cluster --name <cluster_name>
# ~/.kube/config  --> Where the kubernetes config and password have been stored