apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: 100xdevs/env-backend
        ports:
        - containerPort: 3000
        volumeMounts:   # Here we can get the files from our volume which we added.
        - name: env-file
          readOnly: true
          mountPath: "/app/config"
      volumes:    # It will create volumes and add files from secret or config-maps
      - name: env-file
        secret:
          secretName: dotfile-secret