apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  .env: 'REFUQUJBU0VfVVJMOiAnbXlzcWw6Ly9lY29tLWRiOjMzMDYvc2hvcCcKQ0FDSEVfU0laRTogJzEwMDAnClBBWU1FTlRfR0FURVdBWV9VUkw6ICdodHRwczovL3BheW1lbnQtZ2F0ZXdheS5leGFtcGxlLmNvbScKTUFYX0NBUlRfSVRFTVM6ICc1MCcKU0VTU0lPTl9USU1FT1VUOiAnMzYwMCc='