# To start a cluster 

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker


# kind create cluster --config <config_path> --name <cluster_name>
# kind delete cluster --name <cluster_name>
# ~/.kube/config  --> Where the kubernetes config and password have been stored